version: '2'

services:
  escultura-app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.app.ssl
    ports:
      # - "5173:5173"
      - "3089:3089"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=escultura.app.dev2bit.com
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /srv/proxy-web/certs:/etc/nginx/certs:ro
    depends_on:
      - notification-server
    restart: unless-stopped

  notification-server:
    build:
      context: ../notification-server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3089
    env_file:
      - ../notification-server/.env
    volumes:
      - ../notification-server/backup:/app/backup
      - /srv/escultura/notification-server/backup:/app/backup
    restart: unless-stopped

networks:
  default:
    external:
      name: "proxy-web_frontend"

